# Generated by Django 4.2.26 on 2025-11-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candle',
            old_name='open',
            new_name='_open',
        ),
    ]
